"""
This type stub file was generated by pyright.
"""

import sys

"""
Provides Python 2/3 compatibili"""
if sys.version_info >= (3, 0):
    def cls_method_fn(cls, method_name): # -> Any:
        """
        Return the function obj"""
        ...
    
    def is_string(obj): # -> bool:
        """
        Return True if *obj* is"""
        ...
    
else:
    ...
