"""
This type stub file was generated by pyright.
"""

"""
The :mod:`pptx.packaging` modul"""
class CoreProperties:
    """
    Corresponds to part named `"""
    def __init__(self, element) -> None:
        ...
    
    @property
    def author(self):
        ...
    
    @author.setter
    def author(self, value): # -> None:
        ...
    
    @property
    def category(self):
        ...
    
    @category.setter
    def category(self, value): # -> None:
        ...
    
    @property
    def comments(self):
        ...
    
    @comments.setter
    def comments(self, value): # -> None:
        ...
    
    @property
    def content_status(self):
        ...
    
    @content_status.setter
    def content_status(self, value): # -> None:
        ...
    
    @property
    def created(self):
        ...
    
    @created.setter
    def created(self, value): # -> None:
        ...
    
    @property
    def identifier(self):
        ...
    
    @identifier.setter
    def identifier(self, value): # -> None:
        ...
    
    @property
    def keywords(self):
        ...
    
    @keywords.setter
    def keywords(self, value): # -> None:
        ...
    
    @property
    def language(self):
        ...
    
    @language.setter
    def language(self, value): # -> None:
        ...
    
    @property
    def last_modified_by(self):
        ...
    
    @last_modified_by.setter
    def last_modified_by(self, value): # -> None:
        ...
    
    @property
    def last_printed(self):
        ...
    
    @last_printed.setter
    def last_printed(self, value): # -> None:
        ...
    
    @property
    def modified(self):
        ...
    
    @modified.setter
    def modified(self, value): # -> None:
        ...
    
    @property
    def revision(self):
        ...
    
    @revision.setter
    def revision(self, value): # -> None:
        ...
    
    @property
    def subject(self):
        ...
    
    @subject.setter
    def subject(self, value): # -> None:
        ...
    
    @property
    def title(self):
        ...
    
    @title.setter
    def title(self, value): # -> None:
        ...
    
    @property
    def version(self):
        ...
    
    @version.setter
    def version(self, value): # -> None:
        ...
    


