"""
This type stub file was generated by pyright.
"""

"""
Exceptions specific to python-o"""
class OpcError(Exception):
    """
    Base error class for python"""
    ...


class PackageNotFoundError(OpcError):
    """
    Raised when a package canno"""
    ...


