"""
This type stub file was generated by pyright.
"""

"""
Provides the PackURI value type"""
class PackURI(str):
    """
    Provides access to pack URI"""
    _filename_re = ...
    def __new__(cls, pack_uri_str): # -> Self@PackURI:
        ...
    
    @staticmethod
    def from_rel_ref(baseURI, relative_ref): # -> PackURI:
        """
        Return a |PackURI| inst"""
        ...
    
    @property
    def baseURI(self): # -> Self@PackURI:
        """
        The base URI of this pa"""
        ...
    
    @property
    def ext(self): # -> str | Self@PackURI:
        """
        The extension portion o"""
        ...
    
    @property
    def filename(self): # -> Self@PackURI:
        """
        The "filename" portion """
        ...
    
    @property
    def idx(self): # -> int | None:
        """
        Return partname index a"""
        ...
    
    @property
    def membername(self): # -> str:
        """
        The pack URI with the l"""
        ...
    
    def relative_ref(self, baseURI): # -> str:
        """
        Return string containin"""
        ...
    
    @property
    def rels_uri(self): # -> PackURI:
        """
        The pack URI of the .re"""
        ...
    


PACKAGE_URI = ...
CONTENT_TYPES_URI = ...
