"""
This type stub file was generated by pyright.
"""

from docx.opc.shared import lazyproperty

"""Objects that implement reading a"""
class OpcPackage:
    """Main API class for |python-opc|."""
    def __init__(self) -> None:
        ...
    
    def after_unmarshal(self): # -> None:
        """
        Entry point for any pos"""
        ...
    
    @property
    def core_properties(self): # -> Any | CoreProperties:
        """
        |CoreProperties| object"""
        ...
    
    def iter_rels(self): # -> Generator[Any | Unknown, None, None]:
        """
        Generate exactly one re"""
        ...
    
    def iter_parts(self): # -> Generator[Any | Unknown, None, None]:
        """
        Generate exactly one re"""
        ...
    
    def load_rel(self, reltype, target, rId, is_external=...): # -> Any:
        """
        Return newly added |_Re"""
        ...
    
    @property
    def main_document_part(self): # -> Any:
        """
        Return a reference to t"""
        ...
    
    def next_partname(self, template): # -> PackURI | None:
        """Return a |PackURI| instance repr"""
        ...
    
    @classmethod
    def open(cls, pkg_file): # -> Self@OpcPackage:
        """
        Return an |OpcPackage| """
        ...
    
    def part_related_by(self, reltype): # -> Any:
        """
        Return part to which th"""
        ...
    
    @property
    def parts(self): # -> list[Any | Unknown]:
        """
        Return a list containin"""
        ...
    
    def relate_to(self, part, reltype): # -> Any:
        """
        Return rId key of relat"""
        ...
    
    @lazyproperty
    def rels(self): # -> Relationships:
        """
        Return a reference to t"""
        ...
    
    def save(self, pkg_file): # -> None:
        """
        Save this package to *p"""
        ...
    


class Unmarshaller:
    """Hosts static methods for unmarsh"""
    @staticmethod
    def unmarshal(pkg_reader, package, part_factory): # -> None:
        """
        Construct graph of part"""
        ...
    


