"""
This type stub file was generated by pyright.
"""

"""
Provides a general interface to"""
class PhysPkgReader:
    """
    Factory for physical packag"""
    def __new__(cls, pkg_file): # -> _DirPkgReader | _ZipPkgReader:
        ...
    


class PhysPkgWriter:
    """
    Factory for physical packag"""
    def __new__(cls, pkg_file): # -> _ZipPkgWriter:
        ...
    


class _DirPkgReader(PhysPkgReader):
    """
    Implements |PhysPkgReader| """
    def __init__(self, path) -> None:
        """
        *path* is the path to a"""
        ...
    
    def blob_for(self, pack_uri): # -> bytes:
        """
        Return contents of file"""
        ...
    
    def close(self): # -> None:
        """
        Provides interface cons"""
        ...
    
    @property
    def content_types_xml(self): # -> bytes:
        """
        Return the `[Content_Ty"""
        ...
    
    def rels_xml_for(self, source_uri): # -> bytes | None:
        """
        Return rels item XML fo"""
        ...
    


class _ZipPkgReader(PhysPkgReader):
    """
    Implements |PhysPkgReader| """
    def __init__(self, pkg_file) -> None:
        ...
    
    def blob_for(self, pack_uri): # -> bytes:
        """
        Return blob correspondi"""
        ...
    
    def close(self): # -> None:
        """
        Close the zip archive, """
        ...
    
    @property
    def content_types_xml(self): # -> bytes:
        """
        Return the `[Content_Ty"""
        ...
    
    def rels_xml_for(self, source_uri): # -> bytes | None:
        """
        Return rels item XML fo"""
        ...
    


class _ZipPkgWriter(PhysPkgWriter):
    """
    Implements |PhysPkgWriter| """
    def __init__(self, pkg_file) -> None:
        ...
    
    def close(self): # -> None:
        """
        Close the zip archive, """
        ...
    
    def write(self, pack_uri, blob): # -> None:
        """
        Write *blob* to this zi"""
        ...
    


