"""
This type stub file was generated by pyright.
"""

"""
Relationship-related objects.
"""
class Relationships(dict):
    """
    Collection object for |_Rel"""
    def __init__(self, baseURI) -> None:
        ...
    
    def add_relationship(self, reltype, target, rId, is_external=...): # -> _Relationship:
        """
        Return a newly added |_"""
        ...
    
    def get_or_add(self, reltype, target_part): # -> _Relationship:
        """
        Return relationship of """
        ...
    
    def get_or_add_ext_rel(self, reltype, target_ref):
        """
        Return rId of external """
        ...
    
    def part_with_reltype(self, reltype):
        """
        Return target part of r"""
        ...
    
    @property
    def related_parts(self): # -> dict[Unknown, Unknown]:
        """
        dict mapping rIds to ta"""
        ...
    
    @property
    def xml(self): # -> Any:
        """
        Serialize this relation"""
        ...
    


class _Relationship:
    """
    Value object for relationsh"""
    def __init__(self, rId, reltype, target, baseURI, external=...) -> None:
        ...
    
    @property
    def is_external(self): # -> bool:
        ...
    
    @property
    def reltype(self): # -> Unknown:
        ...
    
    @property
    def rId(self): # -> Unknown:
        ...
    
    @property
    def target_part(self): # -> Unknown:
        ...
    
    @property
    def target_ref(self): # -> Unknown:
        ...
    


