"""
This type stub file was generated by pyright.
"""

"""
Objects shared by opc modules.
"""
class CaseInsensitiveDict(dict):
    """
    Mapping type that behaves l"""
    def __contains__(self, key): # -> bool:
        ...
    
    def __getitem__(self, key):
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    


def lazyproperty(f): # -> property:
    """
    @lazyprop decorator. Decora"""
    ...

