"""
This type stub file was generated by pyright.
"""

from ..xmlchemy import BaseOxmlElement

"""
Custom element classes related """
class CT_P(BaseOxmlElement):
    """
    ``<w:p>`` element, containi"""
    pPr = ...
    r = ...
    def add_p_before(self):
        """
        Return a new ``<w:p>`` """
        ...
    
    @property
    def alignment(self): # -> None:
        """
        The value of the ``<w:j"""
        ...
    
    @alignment.setter
    def alignment(self, value): # -> None:
        ...
    
    def clear_content(self): # -> None:
        """
        Remove all child elemen"""
        ...
    
    def set_sectPr(self, sectPr): # -> None:
        """
        Unconditionally replace"""
        ...
    
    @property
    def style(self): # -> None:
        """
        String contained in w:v"""
        ...
    
    @style.setter
    def style(self, style): # -> None:
        ...
    


