"""
This type stub file was generated by pyright.
"""

from docx.shared import Parented

"""Block item container, used by bo"""
class BlockItemContainer(Parented):
    """Base class for proxy objects tha"""
    def __init__(self, element, parent) -> None:
        ...
    
    def add_paragraph(self, text=..., style=...): # -> Paragraph:
        """
        Return a paragraph newl"""
        ...
    
    def add_table(self, rows, cols, width): # -> Table:
        """
        Return a table of *widt"""
        ...
    
    @property
    def paragraphs(self): # -> list[Paragraph]:
        """
        A list containing the p"""
        ...
    
    @property
    def tables(self): # -> list[Table]:
        """
        A list containing the t"""
        ...
    


