"""
This type stub file was generated by pyright.
"""

from docx.blkcntnr import BlockItemContainer
from docx.shared import ElementProxy

"""|Document| and closely related o"""
class Document(ElementProxy):
    """WordprocessingML (WML) document."""
    __slots__ = ...
    def __init__(self, element, part) -> None:
        ...
    
    def add_heading(self, text=..., level=...): # -> Paragraph:
        """Return a heading paragraph newly"""
        ...
    
    def add_page_break(self): # -> Paragraph:
        """Return newly |Paragraph| object """
        ...
    
    def add_paragraph(self, text=..., style=...): # -> Paragraph:
        """
        Return a paragraph newl"""
        ...
    
    def add_picture(self, image_path_or_stream, width=..., height=...): # -> InlineShape:
        """
        Return a new picture sh"""
        ...
    
    def add_section(self, start_type=...): # -> Section:
        """
        Return a |Section| obje"""
        ...
    
    def add_table(self, rows, cols, style=...): # -> Table:
        """
        Add a table having row """
        ...
    
    @property
    def core_properties(self):
        """
        A |CoreProperties| obje"""
        ...
    
    @property
    def inline_shapes(self):
        """
        An |InlineShapes| objec"""
        ...
    
    @property
    def paragraphs(self): # -> list[Paragraph]:
        """
        A list of |Paragraph| i"""
        ...
    
    @property
    def part(self):
        """
        The |DocumentPart| obje"""
        ...
    
    def save(self, path_or_stream): # -> None:
        """
        Save this document to *"""
        ...
    
    @property
    def sections(self): # -> Sections:
        """|Sections| object providing acce"""
        ...
    
    @property
    def settings(self):
        """
        A |Settings| object pro"""
        ...
    
    @property
    def styles(self):
        """
        A |Styles| object provi"""
        ...
    
    @property
    def tables(self): # -> list[Table]:
        """
        A list of |Table| insta"""
        ...
    


class _Body(BlockItemContainer):
    """
    Proxy for ``<w:body>`` elem"""
    def __init__(self, body_elm, parent) -> None:
        ...
    
    def clear_content(self): # -> Self@_Body:
        """
        Return this |_Body| ins"""
        ...
    


