"""
This type stub file was generated by pyright.
"""

"""
Exceptions used with python-doc"""
class PythonDocxError(Exception):
    """
    Generic error class.
    """
    ...


class InvalidSpanError(PythonDocxError):
    """
    Raised when an invalid merg"""
    ...


class InvalidXmlError(PythonDocxError):
    """
    Raised when invalid XML is """
    ...


