"""
This type stub file was generated by pyright.
"""

from docx.opc.package import OpcPackage
from docx.shared import lazyproperty

"""WordprocessingML Package class a"""
class Package(OpcPackage):
    """Customizations specific to a Wor"""
    def after_unmarshal(self): # -> None:
        """Called by loading code after all"""
        ...
    
    def get_or_add_image_part(self, image_descriptor): # -> Any:
        """Return |ImagePart| containing im"""
        ...
    
    @lazyproperty
    def image_parts(self): # -> ImageParts:
        """|ImageParts| collection object f"""
        ...
    


class ImageParts:
    """Collection of |ImagePart| object"""
    def __init__(self) -> None:
        ...
    
    def __contains__(self, item): # -> bool:
        ...
    
    def __iter__(self): # -> Iterator[Unknown]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def append(self, item): # -> None:
        ...
    
    def get_or_add_image_part(self, image_descriptor): # -> ImagePart:
        """Return |ImagePart| object contai"""
        ...
    


