"""
This type stub file was generated by pyright.
"""

from docx.shared import ElementProxy

"""Settings object, providing acces"""
class Settings(ElementProxy):
    """Provides access to document-leve"""
    __slots__ = ...
    @property
    def odd_and_even_pages_header_footer(self):
        """True if this document has distin"""
        ...
    
    @odd_and_even_pages_header_footer.setter
    def odd_and_even_pages_header_footer(self, value): # -> None:
        ...
    


