"""
This type stub file was generated by pyright.
"""

from .shared import Parented

"""
Objects related to shapes, visu"""
class InlineShapes(Parented):
    """
    Sequence of |InlineShape| i"""
    def __init__(self, body_elm, parent) -> None:
        ...
    
    def __getitem__(self, idx): # -> InlineShape:
        """
        Provide indexed access,"""
        ...
    
    def __iter__(self): # -> Generator[InlineShape, None, None]:
        ...
    
    def __len__(self): # -> int:
        ...
    


class InlineShape:
    """
    Proxy for an ``<wp:inline>`"""
    def __init__(self, inline) -> None:
        ...
    
    @property
    def height(self):
        """
        Read/write. The display"""
        ...
    
    @height.setter
    def height(self, cy): # -> None:
        ...
    
    @property
    def type(self): # -> Literal[4, 3, 12, 15, -6]:
        """
        The type of this inline"""
        ...
    
    @property
    def width(self):
        """
        Read/write. The display"""
        ...
    
    @width.setter
    def width(self, cx): # -> None:
        ...
    


