"""
This type stub file was generated by pyright.
"""

from ..part import XmlPart

"""
Core properties part, correspon"""
class CorePropertiesPart(XmlPart):
    """
    Corresponds to part named `"""
    @classmethod
    def default(cls, package): # -> CorePropertiesPart:
        """
        Return a new |CorePrope"""
        ...
    
    @property
    def core_properties(self): # -> CoreProperties:
        """
        A |CoreProperties| obje"""
        ...
    


