"""
This type stub file was generated by pyright.
"""

from ..shared import Parented

"""
Paragraph-related proxy types.
"""
class Paragraph(Parented):
    """
    Proxy object wrapping ``<w:"""
    def __init__(self, p, parent) -> None:
        ...
    
    def add_run(self, text=..., style=...): # -> Run:
        """
        Append a run to this pa"""
        ...
    
    @property
    def alignment(self):
        """
        A member of the :ref:`W"""
        ...
    
    @alignment.setter
    def alignment(self, value): # -> None:
        ...
    
    def clear(self): # -> Self@Paragraph:
        """
        Return this same paragr"""
        ...
    
    def insert_paragraph_before(self, text=..., style=...): # -> Paragraph:
        """
        Return a newly created """
        ...
    
    @property
    def paragraph_format(self): # -> ParagraphFormat:
        """
        The |ParagraphFormat| o"""
        ...
    
    @property
    def runs(self): # -> list[Run]:
        """
        Sequence of |Run| insta"""
        ...
    
    @property
    def style(self):
        """
        Read/Write. |_Paragraph"""
        ...
    
    @style.setter
    def style(self, style_or_name): # -> None:
        ...
    
    @property
    def text(self): # -> Literal['']:
        """
        String formed by concat"""
        ...
    
    @text.setter
    def text(self, text): # -> None:
        ...
    


