"""
This type stub file was generated by pyright.
"""

from ..shared import ElementProxy, lazyproperty

"""
Paragraph-related proxy types.
"""
class ParagraphFormat(ElementProxy):
    """
    Provides access to paragrap"""
    __slots__ = ...
    @property
    def alignment(self): # -> None:
        """
        A member of the :ref:`W"""
        ...
    
    @alignment.setter
    def alignment(self, value): # -> None:
        ...
    
    @property
    def first_line_indent(self): # -> None:
        """
        |Length| value specifyi"""
        ...
    
    @first_line_indent.setter
    def first_line_indent(self, value): # -> None:
        ...
    
    @property
    def keep_together(self): # -> None:
        """
        |True| if the paragraph"""
        ...
    
    @keep_together.setter
    def keep_together(self, value): # -> None:
        ...
    
    @property
    def keep_with_next(self): # -> None:
        """
        |True| if the paragraph"""
        ...
    
    @keep_with_next.setter
    def keep_with_next(self, value): # -> None:
        ...
    
    @property
    def left_indent(self): # -> None:
        """
        |Length| value specifyi"""
        ...
    
    @left_indent.setter
    def left_indent(self, value): # -> None:
        ...
    
    @property
    def line_spacing(self): # -> None:
        """
        |float| or |Length| val"""
        ...
    
    @line_spacing.setter
    def line_spacing(self, value): # -> None:
        ...
    
    @property
    def line_spacing_rule(self): # -> None:
        """
        A member of the :ref:`W"""
        ...
    
    @line_spacing_rule.setter
    def line_spacing_rule(self, value): # -> None:
        ...
    
    @property
    def page_break_before(self): # -> None:
        """
        |True| if the paragraph"""
        ...
    
    @page_break_before.setter
    def page_break_before(self, value): # -> None:
        ...
    
    @property
    def right_indent(self): # -> None:
        """
        |Length| value specifyi"""
        ...
    
    @right_indent.setter
    def right_indent(self, value): # -> None:
        ...
    
    @property
    def space_after(self): # -> None:
        """
        |Length| value specifyi"""
        ...
    
    @space_after.setter
    def space_after(self, value): # -> None:
        ...
    
    @property
    def space_before(self): # -> None:
        """
        |Length| value specifyi"""
        ...
    
    @space_before.setter
    def space_before(self, value): # -> None:
        ...
    
    @lazyproperty
    def tab_stops(self): # -> TabStops:
        """
        |TabStops| object provi"""
        ...
    
    @property
    def widow_control(self): # -> None:
        """
        |True| if the first and"""
        ...
    
    @widow_control.setter
    def widow_control(self, value): # -> None:
        ...
    


