"""
This type stub file was generated by pyright.
"""

from ..shared import ElementProxy

"""
Tabstop-related proxy types.
"""
class TabStops(ElementProxy):
    """
    A sequence of |TabStop| obj"""
    __slots__ = ...
    def __init__(self, element) -> None:
        ...
    
    def __delitem__(self, idx): # -> None:
        """
        Remove the tab at offse"""
        ...
    
    def __getitem__(self, idx): # -> TabStop:
        """
        Enables list-style acce"""
        ...
    
    def __iter__(self): # -> Generator[TabStop, None, None]:
        """
        Generate a TabStop obje"""
        ...
    
    def __len__(self): # -> int:
        ...
    
    def add_tab_stop(self, position, alignment=..., leader=...): # -> TabStop:
        """
        Add a new tab stop at *"""
        ...
    
    def clear_all(self): # -> None:
        """
        Remove all custom tab s"""
        ...
    


class TabStop(ElementProxy):
    """
    An individual tab stop appl"""
    __slots__ = ...
    def __init__(self, element) -> None:
        ...
    
    @property
    def alignment(self):
        """
        A member of :ref:`WdTab"""
        ...
    
    @alignment.setter
    def alignment(self, value): # -> None:
        ...
    
    @property
    def leader(self):
        """
        A member of :ref:`WdTab"""
        ...
    
    @leader.setter
    def leader(self, value): # -> None:
        ...
    
    @property
    def position(self):
        """
        A |Length| object repre"""
        ...
    
    @position.setter
    def position(self, value): # -> None:
        ...
    


