"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import, print_function, unicode_literals

"""
Enumerations used in python-doc"""
class Enumeration:
    @classmethod
    def from_xml(cls, xml_val):
        ...
    
    @classmethod
    def to_xml(cls, enum_val):
        ...
    


