"""
This type stub file was generated by pyright.
"""

from .base import Enumeration, XmlEnumeration, alias

"""
Enumerations used by DrawingML """
class MSO_COLOR_TYPE(Enumeration):
    """
    Specifies the color specifi"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


@alias('MSO_THEME_COLOR')
class MSO_THEME_COLOR_INDEX(XmlEnumeration):
    """
    Indicates the Office theme """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


