"""
This type stub file was generated by pyright.
"""

from .base import XmlEnumeration, alias

"""
Enumerations related to the mai"""
@alias('WD_HEADER_FOOTER')
class WD_HEADER_FOOTER_INDEX(XmlEnumeration):
    """
    alias: **WD_HEADER_FOOTER**"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


@alias('WD_ORIENT')
class WD_ORIENTATION(XmlEnumeration):
    """
    alias: **WD_ORIENT**

    S"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


@alias('WD_SECTION')
class WD_SECTION_START(XmlEnumeration):
    """
    alias: **WD_SECTION**

    """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


