"""
This type stub file was generated by pyright.
"""

"""
Enumerations related to Drawing"""
class WD_INLINE_SHAPE_TYPE:
    """
    Corresponds to WdInlineShap"""
    CHART = ...
    LINKED_PICTURE = ...
    PICTURE = ...
    SMART_ART = ...
    NOT_IMPLEMENTED = ...


WD_INLINE_SHAPE = WD_INLINE_SHAPE_TYPE
