"""
This type stub file was generated by pyright.
"""

from .base import XmlEnumeration, alias

"""
Enumerations related to styles
"""
@alias('WD_STYLE')
class WD_BUILTIN_STYLE(XmlEnumeration):
    """
    alias: **WD_STYLE**

    Sp"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


class WD_STYLE_TYPE(XmlEnumeration):
    """
    Specifies one of the four s"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


