"""
This type stub file was generated by pyright.
"""

from .base import Enumeration, XmlEnumeration, alias

"""
Enumerations related to tables """
@alias('WD_ALIGN_VERTICAL')
class WD_CELL_VERTICAL_ALIGNMENT(XmlEnumeration):
    """
    alias: **WD_ALIGN_VERTICAL*"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


@alias('WD_ROW_HEIGHT')
class WD_ROW_HEIGHT_RULE(XmlEnumeration):
    """
    alias: **WD_ROW_HEIGHT**

 """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


class WD_TABLE_ALIGNMENT(XmlEnumeration):
    """
    Specifies table justificati"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


class WD_TABLE_DIRECTION(Enumeration):
    """
    Specifies the direction in """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


