"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from lxml import etree
from .ns import NamespacePrefixedTag, nsmap
from .shared import CT_DecimalNumber, CT_OnOff, CT_String
from .coreprops import CT_CoreProperties
from .document import CT_Body, CT_Document
from .numbering import CT_Num, CT_NumLvl, CT_NumPr, CT_Numbering
from .section import CT_HdrFtr, CT_HdrFtrRef, CT_PageMar, CT_PageSz, CT_SectPr, CT_SectType
from .settings import CT_Settings
from .shape import CT_Blip, CT_BlipFillProperties, CT_GraphicalObject, CT_GraphicalObjectData, CT_Inline, CT_NonVisualDrawingProps, CT_Picture, CT_PictureNonVisual, CT_Point2D, CT_PositiveSize2D, CT_ShapeProperties, CT_Transform2D
from .styles import CT_LatentStyles, CT_LsdException, CT_Style, CT_Styles
from .table import CT_Height, CT_Row, CT_Tbl, CT_TblGrid, CT_TblGridCol, CT_TblLayoutType, CT_TblPr, CT_TblWidth, CT_Tc, CT_TcPr, CT_TrPr, CT_VMerge, CT_VerticalJc
from .text.font import CT_Color, CT_Fonts, CT_Highlight, CT_HpsMeasure, CT_RPr, CT_Underline, CT_VerticalAlignRun
from .text.paragraph import CT_P
from .text.parfmt import CT_Ind, CT_Jc, CT_PPr, CT_Spacing, CT_TabStop, CT_TabStops
from .text.run import CT_Br, CT_R, CT_Text

"""
Initializes oxml sub-package, i"""
element_class_lookup = ...
oxml_parser = ...
def parse_xml(xml): # -> Any:
    """
    Return root lxml element ob"""
    ...

def register_element_cls(tag, cls): # -> None:
    """
    Register *cls* to be constr"""
    ...

def OxmlElement(nsptag_str, attrs=..., nsdecls=...):
    """
    Return a 'loose' lxml eleme"""
    ...

