"""
This type stub file was generated by pyright.
"""

from docx.oxml.xmlchemy import BaseOxmlElement

"""Custom element classes for core """
class CT_CoreProperties(BaseOxmlElement):
    """
    ``<cp:coreProperties>`` ele"""
    category = ...
    contentStatus = ...
    created = ...
    creator = ...
    description = ...
    identifier = ...
    keywords = ...
    language = ...
    lastModifiedBy = ...
    lastPrinted = ...
    modified = ...
    revision = ...
    subject = ...
    title = ...
    version = ...
    _coreProperties_tmpl = ...
    @classmethod
    def new(cls): # -> Any:
        """
        Return a new ``<cp:core"""
        ...
    
    @property
    def author_text(self): # -> Any | Literal['']:
        """
        The text in the `dc:cre"""
        ...
    
    @author_text.setter
    def author_text(self, value): # -> None:
        ...
    
    @property
    def category_text(self): # -> Any | Literal['']:
        ...
    
    @category_text.setter
    def category_text(self, value): # -> None:
        ...
    
    @property
    def comments_text(self): # -> Any | Literal['']:
        ...
    
    @comments_text.setter
    def comments_text(self, value): # -> None:
        ...
    
    @property
    def contentStatus_text(self): # -> Any | Literal['']:
        ...
    
    @contentStatus_text.setter
    def contentStatus_text(self, value): # -> None:
        ...
    
    @property
    def created_datetime(self): # -> datetime | None:
        ...
    
    @created_datetime.setter
    def created_datetime(self, value): # -> None:
        ...
    
    @property
    def identifier_text(self): # -> Any | Literal['']:
        ...
    
    @identifier_text.setter
    def identifier_text(self, value): # -> None:
        ...
    
    @property
    def keywords_text(self): # -> Any | Literal['']:
        ...
    
    @keywords_text.setter
    def keywords_text(self, value): # -> None:
        ...
    
    @property
    def language_text(self): # -> Any | Literal['']:
        ...
    
    @language_text.setter
    def language_text(self, value): # -> None:
        ...
    
    @property
    def lastModifiedBy_text(self): # -> Any | Literal['']:
        ...
    
    @lastModifiedBy_text.setter
    def lastModifiedBy_text(self, value): # -> None:
        ...
    
    @property
    def lastPrinted_datetime(self): # -> datetime | None:
        ...
    
    @lastPrinted_datetime.setter
    def lastPrinted_datetime(self, value): # -> None:
        ...
    
    @property
    def modified_datetime(self): # -> datetime | None:
        ...
    
    @modified_datetime.setter
    def modified_datetime(self, value): # -> None:
        ...
    
    @property
    def revision_number(self): # -> int:
        """
        Integer value of revisi"""
        ...
    
    @revision_number.setter
    def revision_number(self, value): # -> None:
        """
        Set revision property t"""
        ...
    
    @property
    def subject_text(self): # -> Any | Literal['']:
        ...
    
    @subject_text.setter
    def subject_text(self, value): # -> None:
        ...
    
    @property
    def title_text(self): # -> Any | Literal['']:
        ...
    
    @title_text.setter
    def title_text(self, value): # -> None:
        ...
    
    @property
    def version_text(self): # -> Any | Literal['']:
        ...
    
    @version_text.setter
    def version_text(self, value): # -> None:
        ...
    
    _offset_pattern = ...


