"""
This type stub file was generated by pyright.
"""

from .xmlchemy import BaseOxmlElement

"""
Custom element classes that cor"""
class CT_Document(BaseOxmlElement):
    """
    ``<w:document>`` element, t"""
    body = ...
    @property
    def sectPr_lst(self):
        """
        Return a list containin"""
        ...
    


class CT_Body(BaseOxmlElement):
    """
    ``<w:body>``, the container"""
    p = ...
    tbl = ...
    sectPr = ...
    def add_section_break(self):
        """Return `w:sectPr` element for ne"""
        ...
    
    def clear_content(self): # -> None:
        """
        Remove all content chil"""
        ...
    


