"""
This type stub file was generated by pyright.
"""

"""
Exceptions for oxml sub-package"""
class XmlchemyError(Exception):
    """Generic error class."""
    ...


class InvalidXmlError(XmlchemyError):
    """
    Raised when invalid XML is """
    ...


