"""
This type stub file was generated by pyright.
"""

from .xmlchemy import BaseOxmlElement

"""
Custom element classes related """
class CT_Num(BaseOxmlElement):
    """
    ``<w:num>`` element, which """
    abstractNumId = ...
    lvlOverride = ...
    numId = ...
    def add_lvlOverride(self, ilvl):
        """
        Return a newly added CT"""
        ...
    
    @classmethod
    def new(cls, num_id, abstractNum_id):
        """
        Return a new ``<w:num>`"""
        ...
    


class CT_NumLvl(BaseOxmlElement):
    """
    ``<w:lvlOverride>`` element"""
    startOverride = ...
    ilvl = ...
    def add_startOverride(self, val):
        """
        Return a newly added CT"""
        ...
    


class CT_NumPr(BaseOxmlElement):
    """
    A ``<w:numPr>`` element, a """
    ilvl = ...
    numId = ...


class CT_Numbering(BaseOxmlElement):
    """
    ``<w:numbering>`` element, """
    num = ...
    def add_num(self, abstractNum_id):
        """
        Return a newly added CT"""
        ...
    
    def num_having_numId(self, numId):
        """
        Return the ``<w:num>`` """
        ...
    


