"""
This type stub file was generated by pyright.
"""

from .xmlchemy import BaseOxmlElement

"""
Objects shared by modules in th"""
class CT_DecimalNumber(BaseOxmlElement):
    """
    Used for ``<w:numId>``, ``<"""
    val = ...
    @classmethod
    def new(cls, nsptagname, val):
        """
        Return a new ``CT_Decim"""
        ...
    


class CT_OnOff(BaseOxmlElement):
    """
    Used for ``<w:b>``, ``<w:i>"""
    val = ...


class CT_String(BaseOxmlElement):
    """
    Used for ``<w:pStyle>`` and"""
    val = ...
    @classmethod
    def new(cls, nsptagname, val):
        """
        Return a new ``CT_Strin"""
        ...
    


