"""
This type stub file was generated by pyright.
"""

from ..shared import ElementProxy

"""
DrawingML objects related to co"""
class ColorFormat(ElementProxy):
    """
    Provides access to color se"""
    __slots__ = ...
    def __init__(self, rPr_parent) -> None:
        ...
    
    @property
    def rgb(self): # -> None:
        """
        An |RGBColor| value or """
        ...
    
    @rgb.setter
    def rgb(self, value): # -> None:
        ...
    
    @property
    def theme_color(self): # -> None:
        """
        A member of :ref:`MsoTh"""
        ...
    
    @theme_color.setter
    def theme_color(self, value): # -> None:
        ...
    
    @property
    def type(self): # -> None:
        """
        Read-only. A member of """
        ...
    


