"""
This type stub file was generated by pyright.
"""

from docx.parts.story import BaseStoryPart

"""Header and footer part objects"""
class FooterPart(BaseStoryPart):
    """Definition of a section footer."""
    @classmethod
    def new(cls, package): # -> Self@FooterPart:
        """Return newly created footer part"""
        ...
    


class HeaderPart(BaseStoryPart):
    """Definition of a section header."""
    @classmethod
    def new(cls, package): # -> Self@HeaderPart:
        """Return newly created header part"""
        ...
    


