"""
This type stub file was generated by pyright.
"""

from ..opc.part import XmlPart
from ..shared import lazyproperty

"""
|NumberingPart| and closely rel"""
class NumberingPart(XmlPart):
    """
    Proxy for the numbering.xml"""
    @classmethod
    def new(cls):
        """
        Return newly created em"""
        ...
    
    @lazyproperty
    def numbering_definitions(self): # -> _NumberingDefinitions:
        """
        The |_NumberingDefiniti"""
        ...
    


class _NumberingDefinitions:
    """
    Collection of |_NumberingDe"""
    def __init__(self, numbering_elm) -> None:
        ...
    
    def __len__(self): # -> int:
        ...
    


