"""
This type stub file was generated by pyright.
"""

from ..opc.part import XmlPart

"""
|SettingsPart| and closely rela"""
class SettingsPart(XmlPart):
    """
    Document-level settings par"""
    @classmethod
    def default(cls, package): # -> Self@SettingsPart:
        """
        Return a newly created """
        ...
    
    @property
    def settings(self): # -> Settings:
        """
        A |Settings| proxy obje"""
        ...
    


