"""
This type stub file was generated by pyright.
"""

from docx.opc.part import XmlPart

"""|BaseStoryPart| and related obje"""
class BaseStoryPart(XmlPart):
    """Base class for story parts.

   """
    def get_or_add_image(self, image_descriptor): # -> tuple[Any, Unknown]:
        """Return (rId, image) pair for ima"""
        ...
    
    def get_style(self, style_id, style_type): # -> Any:
        """Return the style in this documen"""
        ...
    
    def get_style_id(self, style_or_name, style_type): # -> Any:
        """Return str style_id for *style_o"""
        ...
    
    def new_pic_inline(self, image_descriptor, width, height): # -> Any:
        """Return a newly-created `w:inline"""
        ...
    
    @property
    def next_id(self): # -> int:
        """Next available positive integer """
        ...
    


