"""
This type stub file was generated by pyright.
"""

from ..opc.part import XmlPart

"""
Provides StylesPart and related"""
class StylesPart(XmlPart):
    """
    Proxy for the styles.xml pa"""
    @classmethod
    def default(cls, package): # -> Self@StylesPart:
        """
        Return a newly created """
        ...
    
    @property
    def styles(self): # -> Styles:
        """
        The |_Styles| instance """
        ...
    


