"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import, division, print_function, unicode_literals
from docx.image.bmp import Bmp
from docx.image.gif import Gif
from docx.image.jpeg import Exif, Jfif
from docx.image.png import Png
from docx.image.tiff import Tiff

"""
Provides objects that can chara"""
SIGNATURES = ...
