"""
This type stub file was generated by pyright.
"""

from .image import BaseImageHeader

class Bmp(BaseImageHeader):
    """
    Image header parser for BMP"""
    @classmethod
    def from_stream(cls, stream): # -> Self@Bmp:
        """
        Return |Bmp| instance h"""
        ...
    
    @property
    def content_type(self): # -> Literal['image/bmp']:
        """
        MIME content type for t"""
        ...
    
    @property
    def default_ext(self): # -> Literal['bmp']:
        """
        Default filename extens"""
        ...
    


