"""
This type stub file was generated by pyright.
"""

"""
Exceptions specific the the ima"""
class InvalidImageStreamError(Exception):
    """
    The recognized image stream"""
    ...


class UnexpectedEndOfFileError(Exception):
    """
    EOF was unexpectedly encoun"""
    ...


class UnrecognizedImageError(Exception):
    """
    The provided image stream c"""
    ...


