"""
This type stub file was generated by pyright.
"""

from .image import BaseImageHeader

class Gif(BaseImageHeader):
    """
    Image header parser for GIF"""
    @classmethod
    def from_stream(cls, stream): # -> Self@Gif:
        """
        Return |Gif| instance h"""
        ...
    
    @property
    def content_type(self): # -> Literal['image/gif']:
        """
        MIME content type for t"""
        ...
    
    @property
    def default_ext(self): # -> Literal['gif']:
        """
        Default filename extens"""
        ...
    


