"""
This type stub file was generated by pyright.
"""

BIG_ENDIAN = ...
LITTLE_ENDIAN = ...
class StreamReader:
    """
    Wraps a file-like object to"""
    def __init__(self, stream, byte_order, base_offset=...) -> None:
        ...
    
    def read(self, count):
        """
        Allow pass-through read"""
        ...
    
    def read_byte(self, base, offset=...): # -> Any:
        """
        Return the int value of"""
        ...
    
    def read_long(self, base, offset=...): # -> Any:
        """
        Return the int value of"""
        ...
    
    def read_short(self, base, offset=...): # -> Any:
        """
        Return the int value of"""
        ...
    
    def read_str(self, char_count, base, offset=...): # -> Any:
        """
        Return a string contain"""
        ...
    
    def seek(self, base, offset=...): # -> None:
        ...
    
    def tell(self):
        """
        Allow pass-through tell"""
        ...
    


