"""
This type stub file was generated by pyright.
"""

from ..shared import lazyproperty

"""
Provides objects that can chara"""
class Image:
    """
    Graphical image stream such"""
    def __init__(self, blob, filename, image_header) -> None:
        ...
    
    @classmethod
    def from_blob(cls, blob): # -> Self@Image:
        """
        Return a new |Image| su"""
        ...
    
    @classmethod
    def from_file(cls, image_descriptor): # -> Self@Image:
        """
        Return a new |Image| su"""
        ...
    
    @property
    def blob(self): # -> Unknown:
        """
        The bytes of the image """
        ...
    
    @property
    def content_type(self):
        """
        MIME content type for t"""
        ...
    
    @lazyproperty
    def ext(self): # -> str* | bytes*:
        """
        The file extension for """
        ...
    
    @property
    def filename(self): # -> Unknown:
        """
        Original image file nam"""
        ...
    
    @property
    def px_width(self):
        """
        The horizontal pixel di"""
        ...
    
    @property
    def px_height(self):
        """
        The vertical pixel dime"""
        ...
    
    @property
    def horz_dpi(self):
        """
        Integer dots per inch f"""
        ...
    
    @property
    def vert_dpi(self):
        """
        Integer dots per inch f"""
        ...
    
    @property
    def width(self): # -> Length:
        """
        A |Length| value repres"""
        ...
    
    @property
    def height(self): # -> Length:
        """
        A |Length| value repres"""
        ...
    
    def scaled_dimensions(self, width=..., height=...): # -> tuple[Length, Length]:
        """
        Return a (cx, cy) 2-tup"""
        ...
    
    @lazyproperty
    def sha1(self): # -> str:
        """
        SHA1 hash digest of the"""
        ...
    


class BaseImageHeader:
    """
    Base class for image header"""
    def __init__(self, px_width, px_height, horz_dpi, vert_dpi) -> None:
        ...
    
    @property
    def content_type(self):
        """
        Abstract property defin"""
        ...
    
    @property
    def default_ext(self):
        """
        Default filename extens"""
        ...
    
    @property
    def px_width(self): # -> Unknown:
        """
        The horizontal pixel di"""
        ...
    
    @property
    def px_height(self): # -> Unknown:
        """
        The vertical pixel dime"""
        ...
    
    @property
    def horz_dpi(self): # -> Unknown:
        """
        Integer dots per inch f"""
        ...
    
    @property
    def vert_dpi(self): # -> Unknown:
        """
        Integer dots per inch f"""
        ...
    


